# Generated by Django 5.2.15 on 2026-06-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteimage',
            name='title',
        ),
        migrations.AddField(
            model_name='siteimage',
            name='name',
            field=models.CharField(default='temp', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
