# Generated by Django 5.2.15 on 2026-06-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('jewelry', 'Jewelry')], default='women', max_length=20),
        ),
    ]
