# Generated by Django 5.2.15 on 2026-06-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='show_on_home',
            field=models.BooleanField(default=False),
        ),
    ]
