# Generated by Django 5.2.15 on 2026-06-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_show_on_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('jewelry', 'Jewelry'), ('bottle', 'Bottle'), ('bag', 'Bag'), ('hat', 'Hat')], default='women', max_length=20),
        ),
    ]
