# Generated by Django 5.2.15 on 2026-06-25 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('jewelry', 'Jewelry'), ('bottle', 'Bottle'), ('bag', 'Bag'), ('hat', 'Hat'), ('shorts', 'Shorts'), ('dress-shirt', 'Dress-Shirt'), ('pants', 'Pants')], default='women', max_length=20),
        ),
    ]
