# Generated by Django 5.2.15 on 2026-06-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('kids', 'Kids'), ('jewelry', 'Jewelry'), ('bottle', 'Bottle'), ('bag', 'Bag'), ('hat', 'Hat'), ('shorts', 'Shorts'), ('dress-shirt', 'Dress-Shirt'), ('pants', 'Pants'), ('tshirt', 'TShirt'), ('kids-t-shirts', 'Kids T-Shirts'), ('jamaica-outfits', 'Jamaica Outfits'), ('kids-dresses', 'Kids Dresses'), ('baby-onesies', 'Baby Onesies'), ('silver-jewelry', 'Silver Jewelry'), ('necklaces', 'Necklaces'), ('bob-marley-bracelets', 'Bob Marley Bracelets'), ('earrings', 'Earrings'), ('baseball', 'Baseball'), ('fedora', 'Fedora'), ('visor', 'Visor'), ('rasta-tams', 'Rasta Tams')], default='women', max_length=20),
        ),
    ]
