# Generated by Django 5.2.15 on 2026-07-05 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('women', 'Women'), ('men', 'Men'), ('kids', 'Kids'), ('jewelry', 'Jewelry'), ('bottle', 'Bottle'), ('hat', 'Hat'), ('shorts', 'Shorts'), ('dress-shirt', 'Dress-Shirt'), ('pants', 'Pants'), ('tshirt', 'TShirt'), ('kids-t-shirts', 'Kids T-Shirts'), ('jamaica-outfits', 'Jamaica Outfits'), ('kids-dresses', 'Kids Dresses'), ('baby-onesies', 'Baby Onesies'), ('silver-jewelry', 'Silver Jewelry'), ('necklaces', 'Necklaces'), ('bob-marley-bracelets', 'Bob Marley Bracelets'), ('earrings', 'Earrings'), ('baseball', 'Baseball'), ('fedora', 'Fedora'), ('visor', 'Visor'), ('rasta-tams', 'Rasta Tams'), ('cigar', 'Cigar'), ('dress', 'Dress'), ('bluse', 'Bluse'), ('womenshirt', 'Womenshirt'), ('hoodies', 'Hoodies'), ('posters', 'Posters'), ('Accessories', 'Accessories'), ('mugs', 'Mugs'), ('thermal-bottles', 'Thermal Bottles'), ('sports-bottles', 'Sports Bottles'), ('sunscreen', 'Sunscreen'), ('souvenirs', 'Souvenirs'), ('bongs', 'Bongs'), ('vape', 'Vape'), ('bags', 'Bags'), ('purse', 'Purse'), ('tote-bags', 'Tote Bags'), ('beach-bags', 'Beach Bags'), ('cover-ups', 'Cover-ups'), ('all-mens-clothing', 'All Mens Clothing'), ('all-womens-clothing', 'All Womens Clothing'), ('all-children', 'All Children'), ('all-jewelry', 'All Jewelry'), ('all-bob-marley', 'All Bob Marley'), ('all-essentials', 'All Essentials'), ('all-bags', 'All Bags'), ('all-caps-and-hats', 'All Caps & Hats'), ('all-bottles', 'All Bottles'), ('all-childrens-clothing', 'All Childrens Clothing')], default='women', max_length=50),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_gallery/')),
                ('angle_name', models.CharField(blank=True, max_length=100)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='store.product')),
            ],
        ),
    ]
